# config.yml
# This value will force issues to use a template for creation. These templates are inspired by the Conventional Commit Githun Repository (https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13)
blank_issues_enabled: false