name: Tests
description: Add missing tests or correct existing tests
title: "test: "
labels: ["testing"]
body:
  - type: textarea
    id: test-change
    attributes:
      label: Testing Change
      description: What tests should be added or corrected?
    validations:
      required: true

  - type: textarea
    id: coverage
    attributes:
      label: Coverage Area
      description: What feature, bug, or module does this cover?